thePalette = [
    ("timer_bg", "black", "black"),
    ("timer_fill", "white", "white"),
    ("start_button", "black", "dark green"),
    ("start_button_focus", "black", "light green"),
    ("reset_button", "black", "dark red"),
    ("reset_button_focus", "black", "light red"),
    ("run_start_button", "white", "dark blue"),
    ("run_start_button_focus", "black", "light cyan"),
    ("run_end_button", "white", "dark blue"),
    ("run_end_button_focus", "black", "light cyan"),
    ("prescale_change_button", "white", "dark blue"),
    ("prescale_change_button_focus", "black", "light cyan"),
    ("persistent_warning_button", "white", "dark blue"),
    ("persistent_warning_button_focus", "black", "light cyan"),
    ("persistent_error_button", "white", "dark blue"),
    ("persistent_error_button_focus", "black", "light cyan"),
    ("error_button", "white", "dark blue"),
    ("error_button_focus", "black", "light cyan"),
    ("other_button", "white", "dark blue"),
    ("other_button_focus", "black", "light cyan"),
    ("shift_start_button", "white", "dark blue"),
    ("shift_start_button_focus", "black", "light cyan"),
    ("shift_end_button", "white", "dark blue"),
    ("shift_end_button_focus", "black", "light cyan"),
    ("write_log_button", "white", "dark blue"),
    ("write_log_button_focus", "black", "light cyan"),
    ("input_form_label", "light blue", "black"),
    ("input_form_edit", "black", "light gray"),
    ("input_form_edit_focus", "white", "black"),
    ("input_form_save_button", "black", "dark green"),
    ("input_form_save_button_focus", "black", "light green"),
    ("input_form_delete_button", "black", "dark red"),
    ("input_form_delete_button_focus", "black", "light red"),
    ("log_event_button", "white", "black"),
    ("log_event_button_focus", "black", "white"),
]
